/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntisemitismusRouteImport } from './routes/antisemitismus'
import { Route as ClankyRouteImport } from './routes/clanky'
import { Route as HledatRouteImport } from './routes/hledat'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as NahlasitIncidentRouteImport } from './routes/nahlasit-incident'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as PodporteNasRouteImport } from './routes/podporte-nas'
import { Route as PtejteSeAiRouteImport } from './routes/ptejte-se-ai'
import { Route as TemataRouteImport } from './routes/temata'
import { Route as VykrikyRouteImport } from './routes/vykriky'
import { Route as ZapojteSeRouteImport } from './routes/zapojte-se'
import { Route as ClankySlugRouteImport } from './routes/clanky.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntisemitismusRoute = AntisemitismusRouteImport.update({
  id: '/antisemitismus',
  path: '/antisemitismus',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankyRoute = ClankyRouteImport.update({
  id: '/clanky',
  path: '/clanky',
  getParentRoute: () => rootRouteImport,
} as any)
const HledatRoute = HledatRouteImport.update({
  id: '/hledat',
  path: '/hledat',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const NahlasitIncidentRoute = NahlasitIncidentRouteImport.update({
  id: '/nahlasit-incident',
  path: '/nahlasit-incident',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnichUdajuRoute = OchranaOsobnichUdajuRouteImport.update({
  id: '/ochrana-osobnich-udaju',
  path: '/ochrana-osobnich-udaju',
  getParentRoute: () => rootRouteImport,
} as any)
const PodporteNasRoute = PodporteNasRouteImport.update({
  id: '/podporte-nas',
  path: '/podporte-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const PtejteSeAiRoute = PtejteSeAiRouteImport.update({
  id: '/ptejte-se-ai',
  path: '/ptejte-se-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const TemataRoute = TemataRouteImport.update({
  id: '/temata',
  path: '/temata',
  getParentRoute: () => rootRouteImport,
} as any)
const VykrikyRoute = VykrikyRouteImport.update({
  id: '/vykriky',
  path: '/vykriky',
  getParentRoute: () => rootRouteImport,
} as any)
const ZapojteSeRoute = ZapojteSeRouteImport.update({
  id: '/zapojte-se',
  path: '/zapojte-se',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankySlugRoute = ClankySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClankyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antisemitismus': typeof AntisemitismusRoute
  '/clanky': typeof ClankyRouteWithChildren
  '/hledat': typeof HledatRoute
  '/manifest': typeof ManifestRoute
  '/nahlasit-incident': typeof NahlasitIncidentRoute
  '/o-nas': typeof ONasRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/podporte-nas': typeof PodporteNasRoute
  '/ptejte-se-ai': typeof PtejteSeAiRoute
  '/temata': typeof TemataRoute
  '/vykriky': typeof VykrikyRoute
  '/zapojte-se': typeof ZapojteSeRoute
  '/clanky/$slug': typeof ClankySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antisemitismus': typeof AntisemitismusRoute
  '/clanky': typeof ClankyRouteWithChildren
  '/hledat': typeof HledatRoute
  '/manifest': typeof ManifestRoute
  '/nahlasit-incident': typeof NahlasitIncidentRoute
  '/o-nas': typeof ONasRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/podporte-nas': typeof PodporteNasRoute
  '/ptejte-se-ai': typeof PtejteSeAiRoute
  '/temata': typeof TemataRoute
  '/vykriky': typeof VykrikyRoute
  '/zapojte-se': typeof ZapojteSeRoute
  '/clanky/$slug': typeof ClankySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antisemitismus': typeof AntisemitismusRoute
  '/clanky': typeof ClankyRouteWithChildren
  '/hledat': typeof HledatRoute
  '/manifest': typeof ManifestRoute
  '/nahlasit-incident': typeof NahlasitIncidentRoute
  '/o-nas': typeof ONasRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/podporte-nas': typeof PodporteNasRoute
  '/ptejte-se-ai': typeof PtejteSeAiRoute
  '/temata': typeof TemataRoute
  '/vykriky': typeof VykrikyRoute
  '/zapojte-se': typeof ZapojteSeRoute
  '/clanky/$slug': typeof ClankySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antisemitismus'
    | '/clanky'
    | '/hledat'
    | '/manifest'
    | '/nahlasit-incident'
    | '/o-nas'
    | '/ochrana-osobnich-udaju'
    | '/podporte-nas'
    | '/ptejte-se-ai'
    | '/temata'
    | '/vykriky'
    | '/zapojte-se'
    | '/clanky/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antisemitismus'
    | '/clanky'
    | '/hledat'
    | '/manifest'
    | '/nahlasit-incident'
    | '/o-nas'
    | '/ochrana-osobnich-udaju'
    | '/podporte-nas'
    | '/ptejte-se-ai'
    | '/temata'
    | '/vykriky'
    | '/zapojte-se'
    | '/clanky/$slug'
  id:
    | '__root__'
    | '/'
    | '/antisemitismus'
    | '/clanky'
    | '/hledat'
    | '/manifest'
    | '/nahlasit-incident'
    | '/o-nas'
    | '/ochrana-osobnich-udaju'
    | '/podporte-nas'
    | '/ptejte-se-ai'
    | '/temata'
    | '/vykriky'
    | '/zapojte-se'
    | '/clanky/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntisemitismusRoute: typeof AntisemitismusRoute
  ClankyRoute: typeof ClankyRouteWithChildren
  HledatRoute: typeof HledatRoute
  ManifestRoute: typeof ManifestRoute
  NahlasitIncidentRoute: typeof NahlasitIncidentRoute
  ONasRoute: typeof ONasRoute
  OchranaOsobnichUdajuRoute: typeof OchranaOsobnichUdajuRoute
  PodporteNasRoute: typeof PodporteNasRoute
  PtejteSeAiRoute: typeof PtejteSeAiRoute
  TemataRoute: typeof TemataRoute
  VykrikyRoute: typeof VykrikyRoute
  ZapojteSeRoute: typeof ZapojteSeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antisemitismus': {
      id: '/antisemitismus'
      path: '/antisemitismus'
      fullPath: '/antisemitismus'
      preLoaderRoute: typeof AntisemitismusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanky': {
      id: '/clanky'
      path: '/clanky'
      fullPath: '/clanky'
      preLoaderRoute: typeof ClankyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hledat': {
      id: '/hledat'
      path: '/hledat'
      fullPath: '/hledat'
      preLoaderRoute: typeof HledatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nahlasit-incident': {
      id: '/nahlasit-incident'
      path: '/nahlasit-incident'
      fullPath: '/nahlasit-incident'
      preLoaderRoute: typeof NahlasitIncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnich-udaju': {
      id: '/ochrana-osobnich-udaju'
      path: '/ochrana-osobnich-udaju'
      fullPath: '/ochrana-osobnich-udaju'
      preLoaderRoute: typeof OchranaOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podporte-nas': {
      id: '/podporte-nas'
      path: '/podporte-nas'
      fullPath: '/podporte-nas'
      preLoaderRoute: typeof PodporteNasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptejte-se-ai': {
      id: '/ptejte-se-ai'
      path: '/ptejte-se-ai'
      fullPath: '/ptejte-se-ai'
      preLoaderRoute: typeof PtejteSeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temata': {
      id: '/temata'
      path: '/temata'
      fullPath: '/temata'
      preLoaderRoute: typeof TemataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vykriky': {
      id: '/vykriky'
      path: '/vykriky'
      fullPath: '/vykriky'
      preLoaderRoute: typeof VykrikyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zapojte-se': {
      id: '/zapojte-se'
      path: '/zapojte-se'
      fullPath: '/zapojte-se'
      preLoaderRoute: typeof ZapojteSeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanky/$slug': {
      id: '/clanky/$slug'
      path: '/$slug'
      fullPath: '/clanky/$slug'
      preLoaderRoute: typeof ClankySlugRouteImport
      parentRoute: typeof ClankyRoute
    }
  }
}

interface ClankyRouteChildren {
  ClankySlugRoute: typeof ClankySlugRoute
}

const ClankyRouteChildren: ClankyRouteChildren = {
  ClankySlugRoute: ClankySlugRoute,
}

const ClankyRouteWithChildren =
  ClankyRoute._addFileChildren(ClankyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntisemitismusRoute: AntisemitismusRoute,
  ClankyRoute: ClankyRouteWithChildren,
  HledatRoute: HledatRoute,
  ManifestRoute: ManifestRoute,
  NahlasitIncidentRoute: NahlasitIncidentRoute,
  ONasRoute: ONasRoute,
  OchranaOsobnichUdajuRoute: OchranaOsobnichUdajuRoute,
  PodporteNasRoute: PodporteNasRoute,
  PtejteSeAiRoute: PtejteSeAiRoute,
  TemataRoute: TemataRoute,
  VykrikyRoute: VykrikyRoute,
  ZapojteSeRoute: ZapojteSeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
