/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntisemitismusRouteImport } from './routes/antisemitismus'
import { Route as ClankyRouteImport } from './routes/clanky'
import { Route as EshopRouteImport } from './routes/eshop'
import { Route as GalerieIncidentuRouteImport } from './routes/galerie-incidentu'
import { Route as HledatRouteImport } from './routes/hledat'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as NahlasitIncidentRouteImport } from './routes/nahlasit-incident'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as PodporteNasRouteImport } from './routes/podporte-nas'
import { Route as PtejteSeAiRouteImport } from './routes/ptejte-se-ai'
import { Route as TemataRouteImport } from './routes/temata'
import { Route as VykrikyRouteImport } from './routes/vykriky'
import { Route as ZapojteSeRouteImport } from './routes/zapojte-se'
import { Route as ClankySlugRouteImport } from './routes/clanky.$slug'
